### ISSUE TITLE
Nerd Fonts patched version

### ISSUE THREAD

**Issue by Manokii** [IdreesInc/Monocraft#35] opened 2022-09-09 19:37 UTC
I think it'll be cool to have a Nerd Fonts patched version of Monocraft

https://github.com/ryanoasis/nerd-fonts/#font-patcher

**Comment by IdreesInc** [comment] 2022-09-10 20:35
Duplicate of https://github.com/IdreesInc/Monocraft/issues/13

**Closed by IdreesInc** 2022-09-10 20:35 UTC
Labels: duplicate
